[build]
  publish = "."
  ignore = false

[[redirects]]
  from = "/api/*"
  to = "https://ava-pwa-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200